version: '3.6'

services:
    api:
      container_name: backend
      image: smart-brain-api
      build: .
      command: npm start
      working_dir: /usr/src/smart-brain-api
      ports:
        - "3001:3001"
      volumes:
        - .:/usr/src/smart-brain-api
